stages:
  - build
  - test

variables:
  KUBERNETES_CPU_REQUEST: "2"
  KUBERNETES_CPU_LIMIT: "2"
  KUBERNETES_MEMORY_REQUEST: "8Gi"
  KUBERNETES_MEMORY_LIMIT: "8Gi"
  KUBERNETES_SERVICE_CPU_REQUEST: "4"
  KUBERNETES_SERVICE_CPU_LIMIT: "4"
  KUBERNETES_SERVICE_MEMORY_REQUEST: "10Gi"
  KUBERNETES_SERVICE_MEMORY_LIMIT: "10Gi"

test:
  stage: test
  image: code-registry.emsl.pnl.gov/multiomics-analyses/pmart_standalone/base-dev:1.4.1
  tags:
    - k8s
    - map
    - rzr
  script:
    - R -e 'options("shiny.testmode");options("shiny.testmode"=TRUE);chromote::get_chrome_args();testthat::test_path();file.path(testthat::test_path(), "../../example_data/test_edata_pep.csv");shiny::runTests()'
  artifacts:
    when: always
    paths:
      - debug_screenshot1.png
      - debug_screenshot2.png
    expire_in: 1 day
    reports:
      junit: junit_result.xml