stages:
  - tests
  
tests:
  stage: tests
  image: code-registry.emsl.pnl.gov/multiomics-analyses/pmart_standalone/base:latest
  tags:
    - map
    - codebuilds
  before_script:
    - |
      apt-get update
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt install -y ./google-chrome-stable_current_amd64.deb
    - R -e "options(repos = c(CRAN = 'https://cloud.r-project.org'));install.packages('testthat');install.packages('shinytest2');install.packages('xml2')"
    - R -e "chromote:::find_chrome()"
  script:
    - R -e 'testthat::test_dir("tests/testthat", reporter = testthat::JunitReporter$new(file = "../../junit_result.xml"))'
  artifacts:
    when: always
    reports:
      junit: junit_result.xml