stages:
  - test
  
test:
  stage: test
  image: code-registry.emsl.pnl.gov/multiomics-analyses/pmart_standalone/base-dev:1.4.1
  tags:
    - k8s
    - map
    - rzr
  script:
    - R -e 'testthat::test_dir("tests/testthat", reporter = testthat::JunitReporter$new(file = "../../junit_result.xml"))'
  artifacts:
    when: always
    reports:
      junit: junit_result.xml