## pmartR-shiny 'base' container.  Installs system and R libraries.

# Install latest version of rocker image
FROM docker.io/rocker/shiny:4.5.2

# Install system libraries (PLEASE ANNOTATE WITH REASON FOR INCLUSION)
# automake:  needed for installation of R package fs
# cmake:  needed for installation of R packages lme4, nloptr, mvdalab 
RUN apt-get update && apt-get install -y \
    sudo \
    pandoc \
    libssl-dev \
    libcurl4-openssl-dev \
    libcairo2-dev \
    libxt-dev \
    libssh2-1-dev \
    libhiredis-dev \
    libzmq3-dev \
    libxml2-dev \
    libcurl3-gnutls \
	vim python3-venv \
	automake \
    cmake

USER root 
WORKDIR /srv/shiny-server/

# pre-install renv
ENV RENV_VERSION 1.0.3
RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'));install.packages('BiocManager')"
RUN R -e "options('repos'=c(CRAN = 'https://cloud.r-project.org'));remotes::install_version('renv', version = '${RENV_VERSION}')"

# Need to set linker flags to install pmartR in linux environment
RUN mkdir $HOME/.R
COPY Makevars-docker .
RUN cp Makevars-docker $HOME/.R/Makevars

# only need this to restore
COPY renv.lock .

# install all packages listed in renv.lock
RUN --mount=type=secret,id=gitlab_pat export GITLAB_PAT="$(cat /run/secrets/gitlab_pat)" \
&& R -e "options(repos=BiocManager::repositories(), pkgType = 'binary');renv::restore(repos=getOption('repos'))"

# install commonly updated packages
RUN --mount=type=secret,id=access_tokens set -a \
&& . /run/secrets/access_tokens && set +a \
&& R -e "renv::install('gitlab@code.emsl.pnl.gov::multiomics-analyses/mapdataaccess-lib@7225058a1563944d2f20b10655cb2b92ae23ed71')" \
&& R -e "options(repos=BiocManager::repositories(), pkgType = 'binary');remotes::install_version('pmartR', version='2.5.1', dependencies=TRUE);"

RUN --mount=type=secret,id=access_tokens set -a \
&& . /run/secrets/access_tokens && set +a \
&& R -e "options(repos=BiocManager::repositories());remotes::install_github('pmartR/malbacR', dependencies=TRUE)"

# Install python dependencies
COPY requirements.txt .
RUN python3 -m venv /venv
RUN /venv/bin/pip install --upgrade pip
RUN /venv/bin/pip install -r requirements.txt
