#

x-app: &x-app
    image: "code-registry.emsl.pnl.gov/multiomics-analyses/pmart_standalone:${TOP_VERSION:-latest}"
    volumes:
        - "./cfg/minio_config.yml:/srv/shiny-server/cfg/minio_config.yml"
    ports:
        - "8300:2800"
    environment:
        - MAP_VERSION=0
    build: &x-app-build
        context: .
        dockerfile: Dockerfile
        args:
            base_tag: "code-registry.emsl.pnl.gov/multiomics-analyses/pmart_standalone/base:${BASE_VERSION:-latest}"

x-test-app: &x-test-app
    <<: *x-app
    volumes:
        - "./cfg/minio_config.yml:/srv/shiny-server/cfg/minio_config.yml"
        - "./tests/.Rprofile_shinytest.R:/srv/shiny-server/.Rprofile"
    environment:
        - MAP_VERSION=1

services:
    app-base:
        profiles: ["local"]
        image: "code-registry.emsl.pnl.gov/multiomics-analyses/pmart_standalone/base:${BASE_VERSION:-latest}"
        container_name: pmart-local
        volumes:
          - "./:/srv/shiny-server/"
          - "/dev/null:/srv/shiny-server/.Rprofile"
        environment:
          - SHINY_DEBUG=${SHINY_DEBUG:-1}
          - MAP_VERSION=${MAP_VERSION:-1}
        <<: *x-app
    pmart-minio:
        profiles: ["minio"]
        container_name: pmart-map
        <<: *x-app
        environment:
            - MAP_VERSION=1
    pmart-test-minio:
        profiles: ["testing"]
        container_name: pmart-map
        <<: *x-test-app
    pmart-test:
        profiles: ["testing"]
        container_name: pmart-local
        <<: *x-test-app
        ports:
            - "8301:2800"
        environment:
            - MAP_VERSION=0
    minio:
        profiles: ["minio", "testing", "local"]
        image: minio/minio
        container_name: minio-map
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server --console-address ":9001" /data

networks:
  default:
    name: pmart-net
