library(shinytest2)

context("basic workflow")

test_that("App completes a basic workflow on peptide-level data", {
  app <- AppDriver$new(name = "pmart_standalone", height = 1199, width = 1299, variant = platform_variant(), timeout = 10000)
  app$set_inputs(datatype = "pep")
  app$set_inputs(upload_collapse_left = "datselect")
  app$upload_file(file_edata = file.path(testthat::test_path(), "../../example_data/AllExample_peptide_labelfree_edata.csv"))
  
  app$set_inputs(upload_collapse_left = "columnids")
  app$wait_for_value(input = "transform")
  app$set_inputs(transform = "log2")
  
  app$wait_for_value(input = "done_idcols")
  app$click("done_idcols")
  app$wait_for_value(input = "emeta_yn")
  app$upload_file(file_emeta = file.path(testthat::test_path(), "../../example_data/AllExample_peptide_labelfree_emeta.csv"))
  app$set_inputs(protein_column = "Protein")
  
  app$click("makeobject")
  
  app$wait_for_value(input = "goto_groups")
  app$click("goto_groups")
  
  # Groups tab
  app$wait_for_value(input = "usevizsampnames")
  app$upload_file(file_fdata = file.path(testthat::test_path(), "../../example_data/AllExample_peptide_labelfree_fdata.csv"))
  app$set_inputs(groups_collapse_left = "fdata_columns")
  app$set_inputs(groups_collapse_right = "fdata_preview")
  
  app$wait_for_value(input = "gcol1")
  app$set_inputs(gcol1 = "Condition1")
  
  app$click("group_designation")
  app$wait_for_value(input = "goto_qc")
  app$click("goto_qc")

  # QC tab
  app$wait_for_value(input = "qc_order_by")
  app$set_inputs(qc_order_by = "Condition1")
  app$set_inputs(qc_color_by = "Condition2")
  app$set_inputs(qc_xlab = "Sampname")
  app$set_inputs(qc_ylab = "log2abund")
  app$set_inputs(qc_title = "New Title")
  app$click("qc_apply_style_plot_1")
  app$click("saveplot")
  
  
  saved_plot <- app$get_value(export = "saved_plot_data")
  expect_equal(digest::digest(saved_plot), "f03ded8dea00a289994a2506ad5442c8")
  
  # check this plot

  # Filter tab
  app$set_inputs(top_page = "filter_tab")
  app$click("add_molfilt")
  app$click("add_cvfilt")
  app$click("add_imdanovafilt")
  app$click("add_profilt")
  app$set_inputs(filter_collapse = character(0))
  app$set_inputs(filter_collapse = "sample_filters")
  app$click("plot_rmdfilt")
  app$click("add_rmdfilt")
  app$set_inputs(filter_collapse = "customfilt")
  app$set_inputs(fdata_customfilt_choices = "Project_C_X_3")
  app$set_inputs(emeta_customfilt_which_values_1 = "1110")
  app$set_inputs(emeta_customfilt_which_values_1 = c("1110", "1192"))
  app$set_inputs(emeta_customfilt_which_values_1 = c("1110", "1192", "1201"))
  app$set_inputs(emeta_customfilt_which_values_1 = c("1110", "1192", "1201", "1205"))
  app$click("add_customfilt")
  app$click("review_filters")
  
  app$wait_for_value(input = "apply_filters")
  app$click("apply_filters")
  
  app$wait_for_value(input = "filter_dismiss")
  app$click("filter_dismiss")
  app$click("goto_norm")
  
  # Normalization
  # app$set_inputs(normalization_sidebar = c("normalize_global_sidebar", "normalize_global_sidebar"))
  # app$set_inputs(spans_submenu = "choose_params")
  # app$set_inputs(spans_or_manual = "spans")
  # app$set_inputs(spans_submenu = "use_spans")
  # app$set_inputs(spans_which_subset_fn = c("all", "los", "complete", "rip", "ppp_rip"))
  # app$set_inputs(spans_which_subset_fn = c("all", "los", "rip", "ppp_rip"))
  # app$set_inputs(spans_which_subset_fn = c("all", "los", "ppp_rip"))
  # app$set_inputs(spans_which_norm_fn = c("mean", "zscore", "mad"))
  # app$click("execute_spans")
  # app$set_inputs(spans_submenu = "choose_params")
  # app$set_inputs(normalization_mainpanel = "spans_mainpanel")
  # app$click("use_selected_spans")
  # app$click("apply_normalization")
  # app$click("normalization_dismiss")
  # app$set_inputs(normalization_sidebar = "normalize_global_sidebar")
  # app$set_inputs(normalization_mainpanel = "normdata_mainpanel")
  # app$click("goto_pepstats")
  # app$set_inputs(peptide_stats_select_method = "imdanova")
  # app$set_inputs(peptide_imdanova_comparison_method = "All pairwise comparisons")
  # app$click("imd_comparison_button_1")
  # app$click("imd_comparison_button_2")
  # app$click("imd_comparison_button_3")
  # app$set_inputs(peptide_imdanova_test_method = "combined")
  # app$click("peptide_apply_imdanova")
  # app$click("pepstats_dismiss")
  # app$click("goto_rollup")
  # app$click("pep_goto_downloads")
  # app$set_inputs(peptide_statistics_collapse_left = character(0))
  # app$set_inputs(`peptide_imdanova-sidepanel-options` = character(0))
  # app$set_inputs(peptide_statistics_collapse_main = "peptide_statistics_plots")
  # app$click("pepstats_dismiss")
  # app$set_inputs(peptide_imdanova_plot_type = "volcano")
  # app$set_inputs(peptide_imdanova_plot_type = "gheatmap")
  # app$set_inputs(top_page = "protein_rollup_tab")
  # app$set_inputs(rollup_sidebar = "isoform_identification")
  # app$set_inputs(bpquant_comps = "A vs B")
  # app$set_inputs(bpquant_comps = c("A vs B", "A vs C"))
  # app$set_inputs(bpquant_comps = c("A vs B", "A vs C", "B vs C"))
  # app$set_inputs(bpquant_max_prot = 4)
  # app$set_inputs(bpquant_lock = TRUE)
  # app$click("bpquant")
  # app$set_inputs(rollup_sidebar = character(0))
  # app$set_inputs(bpquant_apply = "Yes")
  # app$click("apply_rollup")
  # app$set_inputs(which_combine_fn = "mean")
  # app$expect_values()
})
